version: '3'

services:
  scraper:
    build: .
    container_name: scraper-app
    ports:
      - "5001:5001"
    volumes:
      - ${PWD}/data:/app/data
      - ${PWD}/logs:/app/logs
      - ${PWD}/scripts:/app/scripts
      - ${PWD}/static:/app/static
      - ${PWD}/templates:/app/templates
      - ${PWD}/utils:/app/utils
      - ${PWD}/apis:/app/apis
      - ${PWD}/config:/app/config
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATA_DIR=/app/data
      - LOGS_DIR=/app/logs
      - DOCKER_ENV=true
    depends_on:
      - mongodb
    networks:
      - scraper-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - scraper-network

volumes:
  mongodb_data:

networks:
  scraper-network:
    driver: bridge