version: '3'

services:
  scraper:
    build: .
    container_name: scraper-app
    ports:
      - "5001:5001"
    volumes:
      - ${PWD}/data:/app/data  # 将当前目录的 data 文件夹挂载到容器内的 /app/data
      - ${PWD}/logs:/app/logs  # 将当前目录的 logs 文件夹挂载到容器内的 /app/logs
    depends_on:
      - faiss
    environment:
      - DATA_DIR=/app/data   # Docker 容器内的路径
      - LOGS_DIR=/app/logs   # Docker 容器内的路径    
      - FAISS_HOST=faiss     # 依赖的 faiss 服务的 host
      - FAISS_PORT=5002      # 依赖的 faiss 服务的 port
    networks:
      - scraper-network

  faiss:
    image: faiss

  networks:
    scraper-network:
      driver: bridge