DATABASE.USER = "dev"
DATABASE.PASSWORD = "dev"
DATABASE.HOST = "127.0.0.1"
DATABASE.PORT = "6000"
DATABASE.DBNAME = "scraper"
DATABASE.CHARSET = "utf8mb4"
DATABASE.POOL_SIZE = 10
DATABASE.MAX_OVERFLOW = 5
DATABASE.POOL_TIMEOUT = 30
DATABASE.POOL_RECYCLE = 1800